### ISSUE TITLE
Keyboard interaction

### ISSUE THREAD

**Issue by Erk-** [r00ster91/yayagram#2]
Make it possible to control the interface via the keyboard instead of with mouse

**Comment by r00ster91** [comment]
Thank you for your interest!

I have actually thought of this in the past but ultimately decided not to do it at that time because the mouse was meant to be the primary way to select & set cells. Do you mind telling me the use case? Is it a terminal environment that does not support the mouse? Do you mind telling me what kind of environment that is?
`W`, `A`, `S`, `D` is pretty much occupied so that can't be used for controlling the mouse so the next best choice is probably the arrow keys, those could be used for selecting a cell. But which three keys are used to set cells? Perhaps `Delete`, `End` and `Page Down`? So that means that this is could be the area where you play:
![image](https://user-images.githubusercontent.com/35064754/122782884-5f9b7500-d2b1-11eb-901c-4a16191cb130.png)
Which might be pretty convenient. `Delete` would be like left click, `End` middle click and `Page Down` for right click.

However, not all keyboards have this layout. There should be an alternative. Perhaps  `I`, `J`, `K`, `L` could be for movement and arrow key left is left click, down arrow key is middle click and right arrow key is right click?

Do you have opinions on that or ideas?

**Comment by Erk-** [comment]
It is mostly because I find it difficult to be precise with the mousepad, I don't know which constraits being in the terminal lays on the input, so the following may not be completely possible. I was thinking of somthing like QWE to be the mouse keys and then both the vim homerow and the cursor keys being used for movement, it should also work where you for example hold down E for marking cells and then moving the cursor.

**Comment by r00ster91** [comment]
> I was thinking of somthing like QWE to be the mouse keys and then both the vim homerow and the cursor keys being used for movement

That sounds good. `Q`, `W`, `E` are still unreserved. These are now used. Do you mean `H`, `J`, `K`, `L` with Vim home row? It seems rather unusual to use these for cardinal direction movement. Are these keys used in Vim for movement? For now only the arrow keys are supported.

> it should also work where you for example hold down E for marking cells and then moving the cursor.

I'm afraid this is not quite possible as the terminal generally only sends one event at a time as far as I know.

This is now implemented and you can try it on `main` but a release might follow soon.

**Comment by Erk-** [comment]
> 
> 
> > I was thinking of somthing like QWE to be the mouse keys and then both the vim homerow and the cursor keys being used for movement
> 
> That sounds good. `Q`, `W`, `E` are still unreserved. These are now used. Do you mean `H`, `J`, `K`, `L` with Vim home row? It seems rather unusual to use these for cardinal direction movement. Are these keys used in Vim for movement? For now only the arrow keys are supported.

Yeah they are, though arrow keys works well for me
![billede](https://user-images.githubusercontent.com/3659684/123063115-6c34e000-d40d-11eb-9177-5d77c0e27005.png)


> 
> > it should also work where you for example hold down E for marking cells and then moving the cursor.
> 
> I'm afraid this is not quite possible as the terminal generally only sends one event at a time as far as I know.

I assumed so, another possibility would be to have ir such that you clicked once and then enabled it to mark fields until you clicked it again, though I can see that being more annoying, maybe something like a Shift or Ctrl modifier to change behaviour to that?

**Comment by r00ster91** [comment]
I've thought about it for a while and decided to add `K`, `J`, `H`, `L` as well (not yet committed as of writing).

> I assumed so, another possibility would be to have ir such that you clicked once and then enabled it to mark fields until you clicked it again, though I can see that being more annoying, maybe something like a Shift or Ctrl modifier to change behaviour to that?

Yeah this is probably not good behavior by default. I've thought about some ways to possibly use the Shift or Ctrl modifier for that but I couldn't quite think of a way to not make it cumbersome while also not being confusing and I'm not sure I want to sacrifice the simplicity of not handling modifiers for that, which are said to be unreliable sometimes so I think for now this is not going to change but I'm happy it works for you.

**Comment by Maugrift** [comment]
@Erk- (and anyone else who may be interested): I made a fork ([Maugrift/yayagram](https://github.com/Maugrift/yayagram)) that changes the control scheme to use the vi keys. I also added a textual cursor because it can be harder to see where you are when using the keyboard, since you can't just look at where your mouse is.

It does replace the existing control scheme, so I doubt it's a good candidate for a PR. I'm also not a Rust programmer, so I probably wouldn't be able to help create an effective merger or a system for switching between the two control schemes. But in any case, my fork is there if anyone prefers to use the vi keys (like me).

**Comment by r00ster91** [comment]
> I've thought about it for a while and decided to add `K`, `J`, `H`, `L` as well (not yet committed as of writing).
~~Sorry, I've changed my mind, partly because it's becoming quite a lot of keys at this point.~~

Looking back at it, I don't see why HJKL can't be supported for cardinal movement. The only issue would be the <kbd>L</kbd> key for loading but I think that can be changed to <kbd>Enter</kbd>. I've done this in https://github.com/r00ster91/yayagram/commit/34ba64e7a408a66c6f2dc4dab3ef58a09647c001.

Thank you for your contribution! I've featured your fork in the README.

**Comment by Maugrift** [comment]
Cool! I'm glad you were able to find a way to make HJKL work with the existing control scheme. I don't know how much more you plan on adding to yayagram in the future, but I'll try to keep my fork more or less up to date.
